### ISSUE TITLE
Player Controller - special attacks

### ISSUE THREAD

**Issue by sp4ceforc3** [sp4ceforc3/SpaceShooter#5]
-  one special attack per group member (shot with 2, 3 or 4)
-  has a cooldown that is shown on the screen
- effect should be more complex than the previous two
- Adding another laser to the previous attack or just changing its sprite doesn't count
- [x] sp4ceforc3's special
- [x] Domai's special

**Comment by sp4ceforc3** [comment]
#33

**Comment by domai-tb** [comment]
Will close after SpecialDomai is implemented.
